let haiku_arr = [
    {"haiku":"花の色は\n移りにけりな\nいたづらに","translation":"The color of the flowers\nchanges and fades away\nin vain."},
    {"haiku":"古池や\n蛙飛び込む\n水の音","translation":"An old silent pond...\nA frog jumps into the pond,\nSplash! Silence again."},
    {"haiku":"山川に\n風のかけたる\nしがらみは","translation":"In the mountain streams\nthe knots of the winds\ndissolve."},
    {"haiku":"秋風に\nむらさきの山の\n紅葉哉","translation":"Autumn wind -\nmountain's purple hue\nleaves of red"},
    {"haiku":"松の内に\n鳴きつる鳥の\n声きく時","translation":"Deep within the pines,\nA singing bird is heard -\nThe voice of the time."},
    {"haiku":"春の夜の\n夢渡る雲の\nやつがれかな","translation":"On a spring night,\nDrifting clouds -\nWhere do they go?"},
    {"haiku":"夏草や\n兵どもが\n夢の跡","translation":"Summer grass -\nAll that remains\nOf warriors' dreams."},
    {"haiku":"しのぶれど\n色に出でにけり\nわが恋は","translation":"Though I try to hide it,\nIt's clear -\nMy love is showing."},
    {"haiku":"静かなり\n赤蛙鳴くや\n田の中","translation":"So still! A red frog cries out,\nIn the rice paddy."},
    {"haiku":"忘れじの\n身をば思はず\n誓ひてし","translation":"Don't forget me!\nWas written\nBy a woman."},
    {"haiku":"芭蕉も\n言いにくき道を\n行くかな","translation":"Even Matsuo Basho\nfound it difficult to speak\nof the way he went."},
    {"haiku":"しあわせは\nつくるものなり\nうつくしさ","translation":"Happiness is something\nwe create ourselves -\nbeauty within."},
    {"haiku":"青木の\n独り語りぬ\n螢哉","translation":"A tree in the field\nspeaks only to itself,\nfireflies' flickering."},
    {"haiku":"松の間\nやどるとしのぶ\n蟬哉","translation":"In the intervals of\nthe pine needles,\na cicada is hiding."},
    {"haiku":"白雲の\nしばたれども\n明るく","translation":"Even though white clouds\ngathered together,\nit's still bright."},
    {"haiku":"枯朶に\n鶯のこえふ\n春の声","translation":"From a withered bough\na nightingale song -\nthe voice of spring."},
    {"haiku":"葛の花\nからし踏み分け\n鳥の声","translation":"Stepping through the kudzu\nflowers, the bird's song."},
    {"haiku":"夕暮や\n鴉の行方も\nよらぬ雨","translation":"Evening rain -\nwhere the crow goes\nis unclear."},
    {"haiku":"星垣に\n仰ぐる夏の\n白川哉","translation":"Looking up at the stars\nIn the summer night -\nA white river."},
    {"haiku":"青い春\nゆく川にも\n音ある哉","translation":"Blue spring,\nEven in a flowing river,\nThere is sound."},
    {"haiku":"夏草や\n兵どもが\n夢の跡","translation":"Summer grass -\nAll that remains\nOf warriors' dreams."},
    {"haiku":"翆き萌えて\n露の世は春\nけふはけふ","translation":"Fresh green buds -\nThe world of dew is also spring,\nToday and today."},
    {"haiku":"一枝に\n花をもつみそ\n青田哉","translation":"A single branch\nBears flowers -\nThe paddy field in spring."},
    {"haiku":"独らとも\n帰らじ深き\n秋の暮","translation":"Even when alone,\nDo not return home -\nDeep autumn evening."},
    {"haiku":"あしはやみ\n吹く風ふきと\nなりぬれど","translation":"The morning sun\nand the blowing wind\nare both long gone."},
    {"haiku":"夕顔の\n花のあかりの\nこゝろ哉","translation":"The evening glory's\nblossoming light -\nHow heartfelt!"},
    {"haiku":"雲こそ\n立ちどまりせ\n秋の翳","translation":"Clouds -\nThey come to a halt,\nThe autumn shade."},
    {"haiku":"雲とづる\n秋の空白き\n神の川","translation":"Clouds move\nIn the autumn sky,\nThe Milky Way."},
    {"haiku":"朝顔の\n花も束にて\n咲けり哉","translation":"Morning glories\nIn a bunch,\nBlossoming."},
    {"haiku":"菊の花\n咲けるのみの\n霜の朝","translation":"Chrysanthemum flowers\nblossoming only\non a frosty morning."},
    {"haiku":"草の戸も\n住替りてつ\n寒さ哉","translation":"Changing houses,\nEven the grass door -\nFeels cold."},
    {"haiku":"初しぐれ\n瓦の上の\n秋の声","translation":"The first cold raindrops,\nOn the rooftop -\nAutumn's voice."},
    {"haiku":"五月雨に\n風のかおりを\nのこして哉","translation":"The May rains,\nLeaving behind\nthe scent of wind."},
    {"haiku":"青葉風\n日光の山の\nにおひ哉","translation":"Green leaves rustling,\nSunlight on the mountain -\nThe sweet smell."},
    {"haiku":"春風に\nかくれ木のうづら\nのなき哉","translation":"In the spring breeze,\nThe quail\nHides and sings."},
    {"haiku":"青田風\n越えて行く山の\nなほあれど","translation":"The green rice paddies\nI have left behind,\nYet they remain."},
    {"haiku":"海こえて\n逢ふことの\n夏の月","translation":"Beyond the sea,\nMeeting\nunder the summer moon."},
    {"haiku":"世の中は\n花のあとなる\n身のいくに","translation":"The world\nis like a flower,\nits life - fleeting."},
    {"haiku":"夕焼けの\n空より出づる\n虹哉","translation":"From the evening sky\nEmerges\na rainbow."},
    {"haiku":"古里の\nひな祭の夜\n濃く降り","translation":"In my hometown,\nOn the Doll's Festival night,\nThickly falling snow."},
    {"haiku":"初しぐれ\n瓦の上の\n秋の声","translation":"The first cold raindrops,\nOn the rooftop -\nAutumn's voice."}
  ]  